name: "Podcast Generator"
author: "Shamaine Chung"
description: "Generate a feed for a podcast from a yaml file "

runs: 
  using: "docker"
  image: "DockerFile"

branding: 
  icon: "git-branch"
  color: "red"

inputs:
  email: 
    description: "The committer email address"
    required: true
    default: $ {{ github.actor }}@localhost

  name:
    description: "The committer name"
    required: true
    default: $ {{ github.actor }}
